require('plugin_config.telescope')
require('plugin_config.nvim-tree')
require('plugin_config.comment')
require('plugin_config.catpuccin')
require('plugin_config.lualine')
-- require('plugin_config.tabline')
require('plugin_config.barbar')
require('plugin_config.nvim-treesitter')
require('plugin_config.nvim-cmp')
require('plugin_config.lsp')
require('plugin_config.git')
require('plugin_config.telekasten')
require('plugin_config.toggleterm')
